version: '3.6'
volumes:
  node-modules:
    driver: local
services:
  app:
    build: 
      context: ./app
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=8081
    command: bash -c 'npm run dev'
    ports:
      - '8081:8081'
      # - '49153:49153'
    volumes:
      - node-modules:/usr/app/node_modules
      - ./app/:/usr/app/